version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - eledg
    assignees:
      - eledg
    groups:
      actions:
        patterns:
          - '*'
