#!/usr/bin/env bash
set -euo pipefail

get_latest_major() {
  local repo="$1"
  local tag
  tag=$(gh api "repos/$repo/releases/latest" --jq '.tag_name' 2>/dev/null || true)
  if [ -z "$tag" ]; then
    tag=$(gh api "repos/$repo/tags" \
      --jq '[.[].name | select(test("^v[0-9]+"))] | sort | last' 2>/dev/null || true)
  fi
  echo "${tag%%.*}" # strip minor/patch: v6.2.1 → v6
}

mapfile -t action_files < <(
  find . -name 'action.yml' -not -path './.github/*' -not -path './.git/*'
)

# Collect unique repo@version pairs across all composite action files
declare -A seen
for f in "${action_files[@]}"; do
  while IFS= read -r line; do
    [[ "$line" =~ uses:[[:space:]]+(([a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+)@(v[0-9]+)) ]] || continue
    seen["${BASH_REMATCH[2]}@${BASH_REMATCH[3]}"]=1
  done < "$f"
done

has_updates=false
update_lines=()

for key in "${!seen[@]}"; do
  repo="${key%@*}"
  current="${key##*@}"

  latest_tag=$(get_latest_major "$repo")
  if [ -z "$latest_tag" ]; then
    echo "Skipping $repo (could not resolve latest version)"
    continue
  fi

  latest_major="${latest_tag#v}"
  current_major="${current#v}"

  if [[ "$latest_major" =~ ^[0-9]+$ ]] && [ "$latest_major" -gt "$current_major" ]; then
    new_version="v${latest_major}"
    echo "Update: $repo $current → $new_version"
    sed -i "s|uses: ${repo}@${current}|uses: ${repo}@${new_version}|g" "${action_files[@]}"
    update_lines+=("- \`${repo}\`: \`${current}\` → \`${new_version}\`")
    has_updates=true
  else
    echo "Up to date: $repo $current"
  fi
done

if ! $has_updates; then
  echo "All action dependencies are up to date."
  exit 0
fi

branch="deps/action-updates"
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git checkout -b "$branch"
git add -A
git commit -m "chore: update action dependencies"
git push origin "$branch" --force

existing=$(gh pr list --head "$branch" --state open --json number --jq '.[0].number' 2>/dev/null || true)
if [ -z "$existing" ]; then
  gh pr create \
    --title "chore: update action dependencies" \
    --body "$(printf '## Action Dependency Updates\n\nThe following composite actions have updated major versions:\n\n%s\n\n> Auto-generated by the weekly dependency check workflow.' "$(printf '%s\n' "${update_lines[@]}")")" \
    --base main \
    --head "$branch"
else
  echo "PR #$existing already open — branch updated."
fi
